### PR TITLE
update to tpr/vaccination additions to remove dependency of elr_revie…

### PR DESCRIPTION
**Pull request by henryls1**
…w on assemble_data

### CODE REVIEW

**Comment by henryls1** [comment]
New PR for addons to ELR - this time `elr_review.Rmd` does not directly depend on `assemble_data.Rmd`

**Review by thibautjombart — CHANGES_REQUESTED** [review]
Looks good to me - thanks for the speedy patch! 
Trying to run the ELR update locally after updating results for all regions I get:
```
label: unnamed-chunk-17
Quitting from lines 564-605 (elr_review.Rmd) 
Error: Can't subset columns that don't exist.
✖ Column `who_region` doesn't exist.
```
Can you confirm if you get the same on your end?

**Comment by henryls1** [comment]
testing now!

**Comment by henryls1** [comment]
@thibautjombart I cant reproduce the behaviour locally - does the elr data have the `who_region` column when its loaded? You may need to rerun `assemble_data.Rmd` to get this

**Pull request merged**
